services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "9090:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_server.json:/pgadmin4/servers.json

  app:
    image: aex-jar:latest  # para buscar do docker-hub, use rafaelclaumann/aex-jar:latest
    container_name: app-compose
    depends_on:
      - postgres
      - pgadmin
    environment:
      DATABASE_ADDRESS: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  pgadmin_data:
