name: Java CI with Maven

on:
  pull_request:
    branches:
      - 'main'

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 Corretto
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build and package
        run: mvn clean install -B -T 4C

      - name: Save .jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - name: Download .jar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Build Docker image
        run: docker build --no-cache -t aex-jar:test .
